# Generated by Django 2.2.3 on 2019-10-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bairro',
            name='n_criancas',
            field=models.IntegerField(default=0, verbose_name='Número de Criancas'),
            preserve_default=False,
        ),
    ]
