# Generated by Django 2.2.3 on 2019-10-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_bairro_n_criancas'),
    ]

    operations = [
        migrations.AddField(
            model_name='bairro',
            name='uf',
            field=models.CharField(default=1, max_length=3, verbose_name='UF'),
            preserve_default=False,
        ),
    ]
