# Generated by Django 2.2.3 on 2019-10-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_bairro_uf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bairro',
            name='n_criancas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de Criancas'),
        ),
        migrations.AlterField(
            model_name='bairro',
            name='n_criancas_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de crianças com menos de 1 ano'),
        ),
        migrations.AlterField(
            model_name='bairro',
            name='n_idosos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de idosos'),
        ),
        migrations.AlterField(
            model_name='bairro',
            name='n_pessoas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de pessoas'),
        ),
    ]
